# Mémoire allouée à la JVM Gradle
org.gradle.jvmargs=-Xmx2048m -Dfile.encoding=UTF-8

# Obligatoire pour les librairies AndroidX (Jetpack)
android.useAndroidX=true

# Génération de classes R non transitives (plus rapide, recommandé)
android.nonTransitiveRClass=true

# Style de code Kotlin officiel
kotlin.code.style=official
